-- AlterTable
ALTER TABLE "User" ADD COLUMN "largeText" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "showHomeTools" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "defaultAddType" TEXT NOT NULL DEFAULT 'EXPENSE';
ALTER TABLE "User" ADD COLUMN "skipAddConfirm" BOOLEAN NOT NULL DEFAULT false;
