/**
 * Arabic display labels keyed by canonical English Category.name.
 * Stored on Category.nameAr — UI picks by locale; code keeps matching on `name`.
 */
export const CATEGORY_NAME_AR: Record<string, string> = {
  // Personal / house expenses
  Food: 'الطعام',
  'Home food': 'طعام المنزل',
  'Dining & cafés': 'المطاعم والمقاهي',
  'Supermarket food': 'المواد الغذائية',
  'Other food': 'أطعمة أخرى',
  Supermarket: 'مشتريات السوبرماركت',
  'Supermarket cleaning': 'مواد التنظيف',
  'Supermarket household': 'المستلزمات المنزلية',
  'Other supermarket': 'مشتريات أخرى من السوبرماركت',
  Bills: 'الفواتير والخدمات',
  Electricity: 'الكهرباء',
  Water: 'المياه',
  Gas: 'الغاز',
  'Phone bills': 'فواتير الهاتف',
  Internet: 'إنترنت',
  'Other bills': 'فواتير أخرى',
  Housing: 'السكن والمنزل',
  Rent: 'إيجار',
  Insurance: 'تأمين',
  'Home decor': 'الديكور المنزلي',
  'Facility maintenance': 'صيانة مرافق',
  'Appliance repair': 'صيانة الأجهزة',
  'Repairs & fixes': 'الإصلاحات والصيانة',
  'Other home': 'مصروفات منزلية أخرى',
  Transport: 'النقل',
  Fuel: 'الوقود',
  'Car maintenance': 'صيانة السيارة',
  'Car installments': 'أقساط السيارة',
  Rides: 'سيارات الأجرة والتنقل',
  'Other transport': 'مصروفات نقل أخرى',
  Shopping: 'التسوق',
  'Clothes & shoes': 'الملابس والأحذية',
  Electronics: 'إلكترونيات',
  'Electrical appliances': 'أجهزة كهربائية',
  Furniture: 'أثاث',
  Lamps: 'إضاءة ومصابيح',
  'Other shopping': 'مشتريات متنوعة',
  Health: 'الصحة',
  'Doctor visit': 'الزيارات الطبية',
  Medicines: 'أدوية',
  Pharmacy: 'صيدلية',
  'Lab tests': 'الفحوصات والتحاليل',
  'Other health': 'مصروفات صحية أخرى',
  'Personal care': 'العناية الشخصية',
  Beauty: 'التجميل',
  Haircut: 'الحلاقة',
  Cleaning: 'منتجات النظافة',
  'Other care': 'عناية شخصية أخرى',
  Family: 'الأسرة',
  'Pocket money': 'المصروف الشخصي',
  'School needs': 'المستلزمات الدراسية',
  Education: 'تعليم',
  'Family support': 'دعم الأسرة',
  'Social occasions': 'مناسبات اجتماعية',
  'Other family': 'مصروفات أسرية أخرى',
  Lifestyle: 'الترفيه ونمط الحياة',
  Entertainment: 'ترفيه',
  Sports: 'رياضة',
  Subscriptions: 'اشتراكات',
  'Other lifestyle': 'مصروفات ترفيهية أخرى',
  'Travel & trips': 'السفر والرحلات',
  'Travel tickets': 'تذاكر سفر',
  'Travel procedures': 'إجراءات سفر',
  'Local trips': 'رحلات داخلية',
  'Summer resort': 'العطلات الصيفية',
  'Other travel': 'مصروفات سفر أخرى',
  'Charity & sadaqah': 'الصدقات والأعمال الخيرية',
  Mosque: 'مسجد',
  'Ongoing sadaqah': 'صدقة جارية',
  Zakat: 'زكاة',
  Sadaqah: 'صدقة',
  'Help someone': 'مساعدة المحتاجين',
  'Other charity': 'أعمال خيرية أخرى',
  'Loan repayment': 'سداد سلفة',
  Installments: 'أقساط',
  'Apartment installments': 'أقساط السكن',
  'Other installments': 'أقساط أخرى',
  'Government fees': 'الرسوم الحكومية',
  Licenses: 'تراخيص',
  'Traffic fines': 'مخالفات مرور',
  'Other government': 'رسوم حكومية أخرى',
  "Daughters' trousseau": 'تجهيز العروس',
  'Kitchen supplies': 'مستلزمات مطبخ',
  'Kitchen appliances': 'أجهزة مطبخ',
  'Curtains & furnishings': 'الستائر والمفروشات',
  Flooring: 'الأرضيات والسجاد',
  'Trousseau clothes': 'الملابس',
  'Trousseau furniture': 'أثاث',
  'Other trousseau': 'مستلزمات تجهيز أخرى',
  Other: 'أخرى',
  Groceries: 'البقالة والمواد الغذائية',
  'Family gift': 'هدية عائلية',
  Courtesy: 'مجاملات',
  Charity: 'صدقة',
  'Member payback': 'سداد مستحقات فرد',
  Allowance: 'مصروف',
  // Income
  Salary: 'الراتب',
  'Other income': 'دخل آخر',
  'From the house': 'من المنزل',
  // Peer / loans / system
  'Personal loan': 'سلفة شخصية',
  'Help with a bill': 'مساعدة في فاتورة',
  'Outside loan': 'سلفة خارجية',
  'Loan collected': 'تحصيل سلفة',
  'Loan received': 'سلفة مستلمة',
  'Loan repaid': 'سداد سلفة',
  'Wallet transfer': 'تحويل بين المحافظ',
  'Cash withdrawal': 'سحب نقدي',
  'Given to member': 'مصروف لفرد',
};

export function nameArFor(englishName: string): string {
  return CATEGORY_NAME_AR[englishName] ?? '';
}
