/**
 * Arabic display labels keyed by canonical English Category.name.
 * Stored on Category.nameAr — UI picks by locale; code keeps matching on `name`.
 */
export const CATEGORY_NAME_AR: Record<string, string> = {
  // Personal / house expenses
  Food: 'أكل',
  'Home food': 'أكل البيت',
  'Dining & cafés': 'مطاعم وكافيهات',
  'Supermarket food': 'أكل من السوبر',
  'Other food': 'أكل أخرى',
  Supermarket: 'سوبر ماركت',
  'Supermarket cleaning': 'منظفات من السوبر',
  'Supermarket household': 'مستلزمات بيت',
  'Other supermarket': 'سوبر ماركت أخرى',
  Bills: 'فواتير',
  Electricity: 'كهربا',
  Water: 'ميه',
  Gas: 'غاز',
  'Phone bills': 'تليفونات',
  Internet: 'إنترنت',
  'Other bills': 'فواتير أخرى',
  Housing: 'السكن والبيت',
  Rent: 'إيجار',
  Insurance: 'تأمين',
  'Home decor': 'ديكورات',
  'Facility maintenance': 'صيانة مرافق',
  'Appliance repair': 'تصليح أجهزة',
  'Repairs & fixes': 'إصلاحات وصيانات',
  'Other home': 'منزلية أخرى',
  Transport: 'مواصلات',
  Fuel: 'بنزين',
  'Car maintenance': 'صيانة سيارات',
  'Car installments': 'أقساط سيارة',
  Rides: 'التنقل',
  'Other transport': 'مواصلات أخرى',
  Shopping: 'مشتريات',
  'Clothes & shoes': 'ملبوسات وأحذية',
  Electronics: 'إلكترونيات',
  'Electrical appliances': 'أجهزة كهربائية',
  Furniture: 'أثاث',
  Lamps: 'لمبات',
  'Other shopping': 'مشتريات أخرى',
  Health: 'صحة',
  'Doctor visit': 'كشف طبي',
  Medicines: 'أدوية',
  Pharmacy: 'صيدلية',
  'Lab tests': 'تحاليل',
  'Other health': 'صحة أخرى',
  'Personal care': 'عناية شخصية',
  Beauty: 'تجميل',
  Haircut: 'قص شعر',
  Cleaning: 'منظفات',
  'Other care': 'عناية أخرى',
  Family: 'العيلة',
  'Pocket money': 'مصروف جيب',
  'School needs': 'مستلزمات مدرسة',
  Education: 'تعليم',
  'Family support': 'مساعدة أهل',
  'Social occasions': 'مناسبات اجتماعية',
  'Other family': 'عيلة أخرى',
  Lifestyle: 'ترفيه وحياة',
  Entertainment: 'ترفيه',
  Sports: 'رياضة',
  Subscriptions: 'اشتراكات',
  'Other lifestyle': 'ترفيه أخرى',
  'Travel & trips': 'سفر ورحلات',
  'Travel tickets': 'تذاكر سفر',
  'Travel procedures': 'إجراءات سفر',
  'Local trips': 'رحلات داخلية',
  'Summer resort': 'مصيف',
  'Other travel': 'سفر أخرى',
  'Charity & sadaqah': 'أعمال خيرية وصدقات',
  Mosque: 'مسجد',
  'Ongoing sadaqah': 'صدقات جارية',
  Zakat: 'زكاة',
  Sadaqah: 'صدقة',
  'Help someone': 'مساعدة حد',
  'Other charity': 'خيرية أخرى',
  'Loan repayment': 'رد سلفة',
  Installments: 'أقساط',
  'Apartment installments': 'أقساط شقة',
  'Other installments': 'أقساط أخرى',
  'Government fees': 'مصروفات حكومية',
  Licenses: 'تراخيص',
  'Traffic fines': 'مخالفات مرور',
  'Other government': 'حكومية أخرى',
  "Daughters' trousseau": 'تجهيز البنات',
  'Kitchen supplies': 'مستلزمات مطبخ',
  'Kitchen appliances': 'أجهزة مطبخ',
  'Curtains & furnishings': 'مفروشات وستائر',
  Flooring: 'أرضيات وفرش',
  'Trousseau clothes': 'ملبوسات',
  'Trousseau furniture': 'أثاث',
  'Other trousseau': 'تجهيز أخرى',
  Other: 'أخرى',
  Groceries: 'مشتريات',
  'Family gift': 'هدية عيلة',
  Courtesy: 'ضيافة',
  Charity: 'صدقة',
  'Member payback': 'رد فلوس لفرد',
  Allowance: 'مصروف',
  // Income
  Salary: 'مرتب',
  'Other income': 'دخل تاني',
  'From the house': 'من البيت',
  // Peer / loans / system
  'Personal loan': 'سلفة شخصية',
  'Help with a bill': 'مساعدة في فاتورة',
  'Outside loan': 'سلفة برّه',
  'Loan collected': 'تحصيل سلفة',
  'Loan received': 'سلفة مستلمة',
  'Loan repaid': 'رد سلفة',
  'Wallet transfer': 'تحويل بين المحافظ',
  'Cash withdrawal': 'سحب كاش',
  'Given to member': 'إعطاء لفرد',
};

export function nameArFor(englishName: string): string {
  return CATEGORY_NAME_AR[englishName] ?? '';
}
